name: AutoReplace
version: ${project.version}
author: Tim Kalkus
main: com.github.timkalkus.autoreplace.AutoReplaceMain
api-version: 1.16
website: https://www.spigotmc.org/resources/autoreplace.90887/
commands:
  autoreplace:
    permission: autoreplace.command
    permission-message: Permission denied!
    description: The command to change autoreplace settings
    aliases: ar
    usage: "/<command> [<playerName>|@all] [tool|item] [enable|disable|default]"

permissions:
  # general permissions:
  autoreplace.command:
    description: allows to issue the basic command
    default: true
  autoreplace.reload:
    description: allows to reload the config
    default: op
    children:
      - autoreplace.command true
  autoreplace.save:
    description: allows to save current settings to config
    default: op
    children:
      - autoreplace.command true
  # tool permissions:
  autoreplace.tool.change.*:
    description: all tool commands
    default: op
    children:
      - autoreplace.tool.change.own true
      - autoreplace.tool.change.all true
  autoreplace.tool.change.own:
    description: change own tool settings
    default: true
    children:
      - autoreplace.command true
  autoreplace.tool.change.all:
    description: change tool settings for @all and other players
    default: op
    children:
      - autoreplace.command true
  autoreplace.tool.default.true:
    description: flag whether tool replacement is activated by default for group/player
    default: false
  autoreplace.tool.default.false:
    description: flag whether tool replacement is deactivated by default for group/player
    default: false
  autoreplace.tool.forcedefault:
    description: flag whether default tool setting should forcefully overwrite the players own choice with every join
    default: false
  # item permissions:
  autoreplace.item.change.*:
    description: all item commands
    default: op
    children:
      - autoreplace.item.change.own true
      - autoreplace.item.change.all true
  autoreplace.item.change.own:
    description: change own item settings
    default: true
    children:
      - autoreplace.command true
  autoreplace.item.change.all:
    description: change item settings for @all and other players
    default: op
    children:
      - autoreplace.command true
  autoreplace.item.default.true:
    description: flag whether item replacement is activated for group/player
    default: false
  autoreplace.item.default.false:
    description: flag whether item replacement is deactivated for group/player
    default: false
  autoreplace.item.forcedefault:
    description: flag whether default item setting should forcefully overwrite the players own choice with every join
    default: false